### ISSUE TITLE
Enable/disable vimderbar using User Key Map

### ISSUE THREAD

**Issue by glepretre** [daveosborne/brackets-vimderbar#35]
Hi guys,

I would like to add a keybinding toggle vimderbar state (enabled/disabled) using the [User Key Map](https://github.com/adobe/brackets/wiki/User-Key-Bindings) or the [Brackets key remapper extension](https://bitbucket.org/sacah/brackets-key-remapper).

...but I can't find the valid `commandID` (if there is one). I tried `view.enableVimderbar`and `vimderbar.enable`.

Is this actually possible?

**Comment by daveosborne** [comment]
Hey, sorry about the late response, the command to bind is 'fontface.show-vimderbar.view.vimderbar'.  Since that is unneccessarily long, I will update it in the next version to be 'view.enableVimderbar'.

**Comment by glepretre** [comment]
Thanks! I've managed to get my keybinding working (using the Preferences file) :smiley:. Should I leave this issue open until you rename the `commandID`?
