### ISSUE TITLE
i have a problem, The ESC key Invalid

### ISSUE THREAD

**Issue by unixc3t** [daveosborne/brackets-vimderbar#36]
my os is  win8.1 and  64bit 
brackets Release 1.2 build 1.2.0-15689 (master 97c3a4cde) 

I install vimderbar ,

I want to back view mode，i press esc ，but it's invalid

sorry ,my English is so bad，I hope you to understand what i said

**Comment by daveosborne** [comment]
I've got to install the 1.2 pre-release to try this out, hopefully it's a minor change in the keypress handling code. I'll take a look as soon as I can.
