### ISSUE TITLE
Strange macro behavior

### ISSUE THREAD

**Issue by skorlir** [daveosborne/brackets-vimderbar#39]
Here's the definition of the macro:
```
qa
^
cf[
i $headers->set(
esc
f]
cf=
,
esc
$
i )
esc
j
q
```

Here's the code I'm running it on:

```php
  $res['Content-Disposition'] = 'attachment; filename="'. $filename .'"';
  $res['Content-Length'] = '' . filesize($file);
  $res['Content-Range'] = '';
  $res->setBody(file_get_contents($file));
```

And here's what happens when I go to run the macro:

![Screenshot of macro result](https://cloud.githubusercontent.com/assets/887682/6973665/e163cc3c-d951-11e4-94b5-03523ca40338.png)

This seems really unintuitive to me - I don't believe I did anything wrong, macro-definition-wise. Though certainly correct me if I did - I am, at best, at amateur vim user (vimmer? vimolyte?).

EDIT:

This is on OS X 10.9 (not Yosemite), using Brackets Release 1.2 build 1.2.0-15697 (release 8f82e2a97) -- the most up-to-date version of Brackets, so far as I am aware -- and the most recent version of vimderbar as well.

**Comment by daveosborne** [comment]
I'm not sure if the macro is correct for what you want to do, but all of the core vim functionality including macro recording is provided by CodeMirror, check their vim demo (http://codemirror.net/demo/vim.html) and see if the macro works properly there. If it doesn't, then it is likely a bug in CodeMirror vim.
