### ISSUE TITLE
Holding Down Key to Repeat Keystrokes Doesn't Work

### ISSUE THREAD

**Issue by ChrisMarinos** [daveosborne/brackets-vimderbar#40]
On a fresh install of brackets and vimderbar on OSX, keystrokes do not seem to repeat if you hold down the key. For example, holding down j/k to move the cursor up/down a document causes the cursor to move only once. Similarly, holding down the 'a' key in insert mode only causes one 'a' to be inserted.

**Comment by daveosborne** [comment]
Hi Chris, check issue #37 for the same problem, check the codemirror vim demo to see if it happens there. I think it's probably a setting in OSX, but I don't have a mac to check. 

See http://lifehacker.com/5826055/make-your-keyboard-keys-repeat-properly-when-held-down-in-mac-os-x-lion for a possible solution.

**Comment by mocxd** [comment]
this was also happening for me (e.g. holding down "x" wouldn't continue to delete), but now it magically started working for some totally inexplicable reason even though i didn't do anything (except maybe restart brackets a few times here and there). cheers?
