### ISSUE TITLE
New/delete line triggers autocomplete

### ISSUE THREAD

**Issue by scaljeri** [daveosborne/brackets-vimderbar#41]
With VI enabled the autocomplete functionality is triggered when you hit (in command mode) `o` or `dd`. I think that the correct behaviour is to only do this when you start typing (this seems to be the default brackets behaviour). When you do `A` for example, the autocomplete only shows when you start typing, which is good (but inconsistent with `o` and `dd`)! As it works now, it is especially annoying  when, for example, you hit `dd` and want to navigate with the arrow keys, because you then navigate inside the autocomplete dropdown.

Below is a screenshot of what happens when you hit `o` 
![autocomplete](https://cloud.githubusercontent.com/assets/1078741/7450386/8787a3e4-f244-11e4-9fc7-53e1a6c6183c.png).

**Comment by daveosborne** [comment]
I agree completely, I've looked for ways to accomplish this with no joy. Brackets auto complete doesn't let you hook into the showing of hints (up to 1.2, I'll check again). If I could enable/disable auto complete programmatically, this could be solved.

This is by far my largest annoyance using brackets daily. I've just gotten used to it, but would love to fix it.

**Comment by scaljeri** [comment]
Thats to bad. So we just have to wait. Hopefully it can be fixed any time soon! thnx!!

**Comment by mocxd** [comment]
idk if this was already known as part of this issue, but this also happens when hitting "x" or "D", and maybe just when you delete anything at all on the page.  second that this would be a great improvement if can be fixed at some point.  thanks for the great tool tho in general!

**Comment by daveosborne** [comment]
I found a way to prevent the autocomplete from being displayed, give it a try, works nicely for me.

**Comment by mocxd** [comment]
oh yeah! this works great!! :+1:

**Comment by scaljeri** [comment]
very nice, this fix will make it a lot better!!
