### ISSUE TITLE
Change S functionality

### ISSUE THREAD

**Issue by KyleLH** [daveosborne/brackets-vimderbar#44]
In Vim, as well as many of the other vim keybinding plugins I've used, typing S in normal mode deletes everything in the line except indenting spaces/tabs and puts you into insert mode. In your plugin, it simply deletes the whole line (INCLUDING the indenting spaces) and puts you into insert mode. It would be nice if this behaved as expected, especially because vimderbar also disables soft tabs.

**Comment by daveosborne** [comment]
Vimderbar relies on CodeMirror's vim mode for most of it's functionality, this will have to be fixed upstream. It doesn't seem to work on CodeMirror's [demo](http://codemirror.net/demo/vim.html)

As a more immediate fix, I've updated the plugin to support key mappings using the global CodeMirror.Vim.map() function. Add the following to your brackets.json preferences file and update to the new version 0.10.0:

   "vimderbar.mappings": [
        {
            "keys": "S",
            "toKeys": "^D",
            "context": "normal"
        }
    ],

**Comment by daveosborne** [comment]
Oops, this leaves you in normal mode, and was using the wrong attribute (mode, not context), the proper mapping should be:

`
    "vimderbar.mappings": [
        {
            "keys": "S",
            "toKeys": "^Da",
            "mode": "normal"
        }
    ],
`
