### ISSUE TITLE
Buffer/Editor Switch

### ISSUE THREAD

**Issue by jjallen37** [daveosborne/brackets-vimderbar#46]
Hi,

Is there a way to set up buffer switching using \<C-w\> (http://superuser.com/a/486535)? I'm fairly used to this in vim and I keep closing files. I'm new to Brackets so I'm not sure if this would preferably be configure in user keybindings. Also thanks for the plugin! Wouldn't be using Brackets without it.

James

**Comment by daveosborne** [comment]
Hi James,

I've added a command for mapping to switch panes, just add `"Ctrl-W": "view.toggleActivePane"` to your Brackets keymap overrides.

Glad you like the plugin.

Dave
