### ISSUE TITLE
About keymapping and other languages

### ISSUE THREAD

**Issue by verysimplenick** [daveosborne/brackets-vimderbar#47]
Hi, I'm use your extension but need some help with configuring it. For example if your current language not English (russian for example) codemirror can't recognition any commands (for example hjkl navigation) in normal mode. In vim we can map bindings like this:
```
map й q
map ц w
map у e
map к r
map е t
map н y
```
 or setup vim like this:
```
set keymap=russian-jcukenwin
set iminsert=0
set imsearch=0
```
but I'm newbie with codemirror and your vimderbar, please help with setup.

**Comment by verysimplenick** [comment]
map works, but not save after restart brackets, where I can add permanent maps?

**Comment by daveosborne** [comment]
You can add maps in your brackets.json preferences, the format is:

`"vimderbar.mappings": [{
    "keys": "й",
    "toKeys": "q",
    "mode": "normal"
}]`

Mode can be null, "normal", "visual" or "insert" and this corresponds roughly to map, nmap, vmap and imap.
